// assets/appFramework/preact/generate/component/src/gen-name-snake.tsx
/**
 * Gen Name Human component class.
 *
 * @export
 * @class GenNamePascal
 */
import { Component, h } from "preact";
import "./gen-name-snake.css";

export class GenNamePascal extends Component<any, any> {
    /**
     * Message displayed in the view.
     * @type {string}
     */
    public message: string;

    /**
     * Creates an instance of GenNamePascal.
     */
    constructor() {
        super();
        this.message = "Hello Gen Name Human";
    }

    /**
     * Render the component.
     * @returns {JSX.Element}
     */
    public render(): JSX.Element {
        return <span className="gen-name-snake">{ this.message }</span>;
    }
}

// assets/appFramework/angular/generate/component/src/gen-name-snake.component.js
/**
 * Gen Name Human component class.
 *
 * @export
 * @class GenNamePascalComponent
 */
import {Component} from "@angular/core";

@Component({
    moduleId: "genModuleId",
    templateUrl: "./gen-name-snake.component.html",
    styleUrls: ["./gen-name-snake.component.css"]
})
export class GenNamePascalComponent {
    /**
     * Message displayed in the view.
     * @type {string}
     */
    message;

    /**
     * Creates an instance of GenNamePascalComponent.
     */
    constructor() {
        this.message = "Hello Gen Name Human";
    }

    /**
     * The component was initialized.
     * @returns {void}
     */
    ngOnInit() {
        this.message += " - onInit called";
    }
}
